version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
  app:
    build: .
    image: zcy4coding/talk_demo:latest
    entrypoint: entrypoint.sh
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db